# Generated by Django 5.2.4 on 2025-11-11 09:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deskApp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDesk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_desks', to='deskApp.table')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_desks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
