# Generated by Django 5.2.8 on 2025-11-13 10:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deskApp', '0003_alter_userdesk_table_alter_userdesk_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sitting', models.FloatField(blank=True, help_text='Preferred sitting height in cm', null=True)),
                ('standing', models.FloatField(blank=True, help_text='Preferred standing height in cm', null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
